# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blockid', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentid', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=50)),
                ('registertime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
    ]
