# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170824_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachids',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
